#!/usr/bin/php
<?php
// Gather PHP files that need to be checked.
exec("git diff --name-only --diff-filter=ACM | egrep '.php$'", $files);

// Remove empty lines.
$files = array_filter('empty', array_map('trim', $files));

var_dump($files);

exit(1);

// Determine the phpunit configuration file.
$configuration = realpath(__DIR__ '/../../test/phpunit.xml');

// If we found files, go test them.
if (count($files)) {
    exec("phpunit -c {$configuration}", $output, $returnCode);

    // If it fails, show how and why.
    if ($returnCode !== 0) {
        echo implode("\n", $output) . "\n\nABORTING COMMIT!\n";
    }

    exit($returnCode);
}

// Move along.
exit(0);
